version: 2
sources:
  - name: erp
    database: fea24_4
    schema: raw_northwind
    tables:
      - name: product
      - name: category
      - name: supplier
      - name: _order_
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: orderdetail
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: employee